apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: cruder-app
  labels:
    app: cruder
    component: configuration
data:
  # Database configuration (non-sensitive)
  DB_HOST: "postgres-service"
  # for local debug - specify IP for host.minikube.internal here like DB_HOST: "192.168.49.1"
  DB_PORT: "5432"
  DB_NAME: "testdb"

  # Application configuration
  GIN_MODE: "release"

  # Server configuration
  SERVER_PORT: "8080"
